### ISSUE TITLE
feat: cron jobs and storing notice

### ISSUE THREAD

**Issue by sidmohanty11** [EduHeat/noticeboard#5]
- Add the scraped data to mongo storage
- if it's a new notice, set isNew tag to true
- Add nodecron, which will keep track of all notice

Overall schema,
```
Notice : {
  id : string
  notice: string
  date: string
  url: string
  isNew: boolean
}
```

**Comment by subrat0796** [comment]
How exactly this feature would be working?

Let's say we are scrapping the website every 1 hour
We get the allNotice object .

Now we will do a check in the database with the allNotice object ( check the URL part of the object )

if the URL is found then we will mark that notice's isNew to false

if the URL is not found then we will create a new notice's with the isNew as true?

Shall we delete the previous notices? ( or keep them so that we can do some route /getallnotices and with that route, we will be giving all the notices to the user )

@sidmohanty11

**Comment by sidmohanty11** [comment]
@subrat0796 

> if the URL is not found then we will create a new notice's with the isNew as true?

yes, if the first URL matches the stored URL then we just return and do nothing (no db transactions) but if there is a new URL we can just loop through till we get a match right? And we can just add them with isNew true

**Comment by sidmohanty11** [comment]
> Shall we delete the previous notices? ( or keep them so that we can do some route /getallnotices and with that route, we will be giving all the notices to the user )

What do you suggest?

**Comment by subrat0796** [comment]
> > Shall we delete the previous notices? ( or keep them so that we can do some route /getallnotices and with that route, we will be giving all the notices to the user )
> 
> What do you suggest?

I would suggest to keep two routes . 
Let's say the first route is /api/notice/new - which will give us the new notice 
second route is /api/notice/all - which will give us all the rest notices

See what I thought was whenever we visit a noticeboard , we see the recent notice . But many a times we also see the previous notice too . 

I want our users to remain engaged in our platform . Like we are giving them new Notice . 
Suppose they also wanted to see the recent previous notices . We can also provide them that too

@sidmohanty11  What is your thought to this one ?

**Comment by subrat0796** [comment]
> > Shall we delete the previous notices? ( or keep them so that we can do some route /getallnotices and with that route, we will be giving all the notices to the user )
> 
> What do you suggest?

@sidmohanty11

**Comment by sidmohanty11** [comment]
> > > Shall we delete the previous notices? ( or keep them so that we can do some route /getallnotices and with that route, we will be giving all the notices to the user )
> > 
> > 
> > What do you suggest?
> 
> I would suggest to keep two routes . Let's say the first route is /api/notice/new - which will give us the new notice second route is /api/notice/all - which will give us all the rest notices
> 
> See what I thought was whenever we visit a noticeboard , we see the recent notice . But many a times we also see the previous notice too .
> 
> I want our users to remain engaged in our platform . Like we are giving them new Notice . Suppose they also wanted to see the recent previous notices . We can also provide them that too

Got it, lets do that.

Just not sure about this part,
> Let's say the first route is /api/notice/new - which will give us the new notice
second route is /api/notice/all - which will give us all the rest notices

This will make two API calls on the same page. Or are we planning for multiple pages?

**Comment by sidmohanty11** [comment]
PS: For now, I think it's better to stick with the current model imho, as we can fetch both 
- new notice
- prev notice

store them in mongo and show them completely if we want, what do you think?

**Comment by subrat0796** [comment]
> > > > Shall we delete the previous notices? ( or keep them so that we can do some route /getallnotices and with that route, we will be giving all the notices to the user )
> > > 
> > > 
> > > What do you suggest?
> > 
> > 
> > I would suggest to keep two routes . Let's say the first route is /api/notice/new - which will give us the new notice second route is /api/notice/all - which will give us all the rest notices
> > See what I thought was whenever we visit a noticeboard , we see the recent notice . But many a times we also see the previous notice too .
> > I want our users to remain engaged in our platform . Like we are giving them new Notice . Suppose they also wanted to see the recent previous notices . We can also provide them that too
> 
> Got it, lets do that.
> 
> Just not sure about this part,
> 
> > Let's say the first route is /api/notice/new - which will give us the new notice
> > second route is /api/notice/all - which will give us all the rest notices
> 
> This will make two API calls on the same page. Or are we planning for multiple pages?

I am planning for multiple pages .

Our push notification would be of new notice . 

There would be some button on that page to show all the notices , which when clicked will show all the notices ( from latest to oldest )

Does this sound good ?

Or if not then we can drop the idea of all notice

@sidmohanty11

**Comment by sidmohanty11** [comment]
Let's keep it a single page with the current architecture as we planned. We'll scale it as we go. As we don't even know if "old notice" is relevant enough for the students (as of now)

As of now let's just think about the push notification for new notice @subrat0796

**Comment by subrat0796** [comment]
> Let's keep it a single page with the current architecture as we planned. We'll scale it as we go. As we don't even know if "old notice" is relevant enough for the students (as of now)
> 
> As of now let's just think about the push notification for new notice

Okay cool . 

I am implementing the new notice part as I mentioned above in the thread .  @sidmohanty11

**Comment by sidmohanty11** [comment]
Cool! @subrat0796 👍
